blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/jonasduerto/elementor-hosting-pricing/discussions
    about: Ask questions and share ideas in Discussions.
