name: Feature request
description: Suggest an idea for the Elementor Hosting Pricing plugin
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description of the feature
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How should it work? Any UI or technical details?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
